// Story progression and unlock requirements.
// Requirement tokens: 'chN' = reached chapter N (chapter N-1 marked complete); anything else = a story/start id that must be ticked.
// Chapters 7/8 are Epilogue parts 1/2. Pins marked approx are placed by area, not exact spot.
RDR.story = {
  chapters: [
    { n: 1, name: "Chapter 1", place: "Colter", camp: [-33.83, 122.99], missions: [
      ["outlaws-from-the-west", "Outlaws from the West"],
      ["enter-pursued-by-a-memory", "Enter, Pursued by a Memory"],
      ["the-aftermath-of-genesis", "The Aftermath of Genesis"],
      ["old-friends", "Old Friends"],
      ["who-the-hell-is-leviticus-cornwall", "Who the Hell is Leviticus Cornwall?"],
      ["eastward-bound", "Eastward Bound"],
    ] },
    { n: 2, name: "Chapter 2", place: "Horseshoe Overlook", camp: [-85.07, 144.83], missions: [
      ["polite-society-valentine-style", "Polite Society, Valentine Style"],
      ["americans-at-rest", "Americans at Rest"],
      ["exit-pursued-by-a-bruised-ego", "Exit Pursued by a Bruised Ego"],
      ["paying-a-social-call", "Paying a Social Call"],
      ["a-quiet-time", "A Quiet Time"],
      ["the-spines-of-america", "The Spines of America"],
      ["blessed-are-the-meek", "Blessed are the Meek?"],
      ["who-is-not-without-sin", "Who is Not Without Sin"],
      ["the-first-shall-be-last", "The First Shall Be Last"],
      ["the-sheep-and-the-goats", "The Sheep and the Goats"],
      ["a-strange-kindness", "A Strange Kindness"],
      ["pouring-forth-oil-i", "Pouring Forth Oil I"],
      ["pouring-forth-oil-ii", "Pouring Forth Oil II", 1],
      ["pouring-forth-oil-iii", "Pouring Forth Oil III"],
      ["pouring-forth-oil-iv", "Pouring Forth Oil IV"],
      ["a-fisher-of-men", "A Fisher of Men"],
      ["an-american-pastoral-scene", "An American Pastoral Scene"],
      ["good-honest-snake-oil", "Good, Honest, Snake Oil", 1],
      ["we-loved-once-and-true-i", "We Loved Once and True I", 1],
      ["we-loved-once-and-true-ii", "We Loved Once and True II", 1],
      ["we-loved-once-and-true-iii", "We Loved Once and True III", 1],
      ["money-lending-and-other-sins-i", "Money Lending and Other Sins I", 1],
      ["money-lending-and-other-sins-ii", "Money Lending and Other Sins II", 1],
      ["money-lending-and-other-sins-iii", "Money Lending and Other Sins III", 1],
    ] },
    { n: 3, name: "Chapter 3", place: "Clemens Point", camp: [-110.12, 163.16], missions: [
      ["further-questions-of-female-suffrage", "Further Questions of Female Suffrage"],
      ["the-new-south", "The New South"],
      ["the-course-of-true-love-i", "The Course of True Love I", 1],
      ["the-course-of-true-love-ii", "The Course of True Love II", 1],
      ["the-course-of-true-love-iii", "The Course of True Love III", 1],
      ["american-distillation", "American Distillation"],
      ["an-honest-mistake", "An Honest Mistake"],
      ["preaching-forgiveness-as-he-went", "Preaching Forgiveness as He Went"],
      ["sodom-back-to-gomorrah", "Sodom? Back to Gomorrah"],
      ["advertising-the-new-american-art", "Advertising, The New American Art"],
      ["magicians-for-sport", "Magicians for Sport"],
      ["the-fine-joys-of-tobacco", "The Fine Joys of Tobacco"],
      ["horse-flesh-for-dinner", "Horse Flesh for Dinner"],
      ["friends-in-very-low-places", "Friends in Very Low Places"],
      ["blessed-are-the-peacemakers", "Blessed are the Peacemakers"],
      ["a-short-walk-in-a-pretty-town", "A Short Walk in a Pretty Town"],
      ["blood-feuds-ancient-and-modern", "Blood Feuds, Ancient and Modern"],
      ["the-battle-of-shady-belle", "The Battle of Shady Belle"],
      ["money-lending-and-other-sins-iv", "Money Lending and Other Sins IV", 1],
    ] },
    { n: 4, name: "Chapter 4", place: "Saint Denis (camp: Shady Belle)", camp: [-125.65, 188.91], missions: [
      ["the-joys-of-civilization", "The Joys of Civilization"],
      ["no-no-and-thrice-no", "No, No and Thrice, No"],
      ["angelo-bronte-a-man-of-honor", "Angelo Bronte, A Man of Honor"],
      ["help-a-brother-out", "Help a Brother Out", 1],
      ["brothers-and-sisters-one-and-all", "Brothers and Sisters, One and All", 1],
      ["the-gilded-cage", "The Gilded Cage"],
      ["a-fine-night-of-debauchery", "A Fine Night of Debauchery"],
      ["horsemen-apocalypses", "Horsemen, Apocalypses"],
      ["urban-pleasures", "Urban Pleasures"],
      ["country-pursuits", "Country Pursuits"],
      ["revenge-is-a-dish-best-eaten", "Revenge is a Dish Best Eaten"],
      ["fatherhood-and-other-dreams", "Fatherhood and Other Dreams", 1],
      ["american-fathers-i", "American Fathers I", 1],
      ["american-fathers-ii", "American Fathers II", 1],
      ["banking-the-old-american-art", "Banking, The Old American Art"],
      ["lost-and-not-quite-found", "Lost and Not Quite Found", 1],
      ["money-lending-and-other-sins-v", "Money Lending and Other Sins V", 1],
    ] },
    { n: 5, name: "Chapter 5", place: "Guarma", missions: [
      ["welcome-to-the-new-world", "Welcome to the New World"],
      ["a-kind-and-benevolent-despot", "A Kind and Benevolent Despot"],
      ["savagery-unleashed", "Savagery Unleashed"],
      ["hell-hath-no-fury", "Hell Hath No Fury"],
      ["paradise-mercifully-departed", "Paradise Mercifully Departed"],
      ["dear-uncle-tacitus", "Dear Uncle Tacitus"],
      ["fleeting-joy", "Fleeting Joy"],
    ] },
    { n: 6, name: "Chapter 6", place: "Beaver Hollow", camp: [-56.23, 197.51], missions: [
      ["thats-murfree-country", "That's Murfree Country"],
      ["a-fork-in-the-road", "A Fork in the Road"],
      ["icarus-and-friends", "Icarus and Friends"],
      ["visiting-hours", "Visiting Hours"],
      ["just-a-social-call", "Just a Social Call"],
      ["the-delights-of-van-horn", "The Delights of Van Horn"],
      ["a-rage-unleashed", "A Rage Unleashed"],
      ["goodbye-dear-friend", "Goodbye, Dear Friend"],
      ["archeology-for-beginners", "Archeology for Beginners", 1],
      ["honor-amongst-thieves", "Honor, Amongst Thieves", 1],
      ["the-fine-art-of-conversation", "The Fine Art of Conversation"],
      ["favored-sons", "Favored Sons"],
      ["the-kings-son", "The King's Son"],
      ["mrs-sadie-adler-widow-i", "Mrs. Sadie Adler, Widow I"],
      ["mrs-sadie-adler-widow-ii", "Mrs. Sadie Adler, Widow II"],
      ["the-bridge-to-nowhere", "The Bridge to Nowhere"],
      ["my-last-boy", "My Last Boy"],
      ["our-best-selves", "Our Best Selves"],
      ["red-dead-redemption", "Red Dead Redemption"],
      ["the-course-of-true-love-iv", "The Course of True Love IV", 1],
      ["the-course-of-true-love-v", "The Course of True Love V", 1],
      ["money-lending-and-other-sins-vi", "Money Lending and Other Sins VI", 1],
      ["money-lending-and-other-sins-vii", "Money Lending and Other Sins VII", 1],
      ["do-not-seek-absolution-i", "Do Not Seek Absolution I", 1],
      ["do-not-seek-absolution-ii", "Do Not Seek Absolution II", 1],
      ["of-men-and-angels-i", "Of Men and Angels I", 1],
      ["of-men-and-angels-ii", "Of Men and Angels II", 1],
    ] },
    { n: 7, name: "Epilogue Part 1", place: "Pronghorn Ranch", camp: [-74.98, 96.75], missions: [
      ["the-wheel", "The Wheel"],
      ["simple-pleasures", "Simple Pleasures"],
      ["farming-for-beginners", "Farming, For Beginners"],
      ["fatherhood-for-beginners", "Fatherhood, For Beginners"],
      ["old-habits", "Old Habits"],
      ["fatherhood-for-idiots", "Fatherhood, For Idiots"],
      ["jim-milton-rides-again", "Jim Milton Rides, Again?"],
      ["motherhood", "Motherhood"],
      ["gainful-employment", "Gainful Employment"],
      ["the-landowning-classes", "The Landowning Classes"],
      ["home-of-the-gentry", "Home of the Gentry?"],
    ] },
    { n: 8, name: "Epilogue Part 2", place: "Beecher's Hope", camp: [-113.78, 113.37], missions: [
      ["bare-knuckle-friendships", "Bare Knuckle Friendships"],
      ["an-honest-days-labors", "An Honest Day's Labors"],
      ["home-improvement-for-beginners", "Home Improvement for Beginners"],
      ["the-tool-box", "The Tool Box"],
      ["a-new-jerusalem", "A New Jerusalem"],
      ["a-quick-favor-for-an-old-friend", "A Quick Favor for an Old Friend"],
      ["uncles-bad-day", "Uncle's Bad Day"],
      ["the-best-of-women", "The Best of Women"],
      ["trying-again", "Trying Again"],
      ["a-really-big-bastard", "A Really Big Bastard"],
      ["a-new-future-imagined", "A New Future Imagined"],
      ["american-venom", "American Venom"],
    ] },
  ],

  // People to meet / things to pick up before a collection opens. Shown as pins until ticked.
  // approx: 1 = no game-data position exists; pinned from the guides' directions only.
  starts: [
    { id: 'start-deborah', ch: 2, who: 'Deborah MacGuinness', mission: 'A Test of Faith', unlocks: 'dino', l: [-89.32, 151.75],
      d: 'Elderly woman crouched in a crater in The Heartlands, northeast of Flatneck Station. Mail bone locations to her from any post office.' },
    { id: 'start-sinclair', ch: 3, who: 'Francis Sinclair', mission: 'Geology for Beginners', unlocks: 'carving', l: [-90.46, 103.78],
      d: 'Sitting outside his cabin northwest of Strawberry (north of the "S" in Strawberry). Available once Chapter 2 is complete.' },
    { id: 'start-gill', ch: 3, who: 'Jeremy Gill', mission: 'A Fisher of Fish', unlocks: 'fish', l: [-99.7, 156.16],
      d: 'His fishing shack on the northeast bank of Flat Iron Lake (the "Rare Fish Shack" in the game files). Buy special lures at the Lagras bait shop.' },
    { id: 'start-hunt', ch: 2, who: 'Hunting Request letter', mission: 'Hunting Requests', unlocks: 'hunt', l: [-72.32, 145.46],
      d: 'Pick up the first Hunting Request at a post office or train station: Valentine post office shown (also Strawberry, Rhodes, Saint Denis, Van Horn). Mail carcasses to Mrs. Hobbs.' },
    { id: 'start-wasp', ch: 4, who: 'Algernon Wasp', mission: 'Duchesses and Other Animals', unlocks: 'exotic', l: [-106.48, 202.9], after: 'the-gilded-cage',
      d: 'In the iron greenhouse behind the big blue house in north Saint Denis. Appears after "The Gilded Cage".' },
    { id: 'start-charlotte', ch: 6, who: 'Charlotte Balfour', mission: "The Widow of Willard's Rest", unlocks: 'loot', l: [-38.83, 210.79],
      d: "Willard's Rest, far northeast Roanoke Ridge. Help her and she leaves you a box of money (Willard's Rest stash)." },
  ],

  // Category-wide requirements (everything also needs Chapter 2: free roam opens after Colter).
  // Graves can only be visited once the story is finished (ch9 = after Epilogue Part 2).
  catReq: {
    dino: ['ch2', 'start-deborah'], carving: ['ch3', 'start-sinclair'], dream: ['ch2'], card: ['ch2'], treasure: ['ch2'], grave: ['ch9'],
    animal: ['ch2', 'exit-pursued-by-a-bruised-ego'], fish: ['ch3', 'start-gill'], hunt: ['ch2', 'start-hunt'],
    exotic: ['ch4', 'the-gilded-cage', 'start-wasp'], gang: ['ch2'], gear: ['ch2'], loot: ['ch2'],
  },
  // Extra per-item requirements, on top of the category ones (gang requests carry their own chapter in data.js).
  itemReq: {
    'treasure-landmarks-map1': ['ch7'],
    'treasure-elemental-map1': ['ch8'],
    'hunt-5-waxwing': ['ch7'], 'hunt-5-bat': ['ch7'], 'hunt-5-blue-jay': ['ch7'], 'hunt-5-crow': ['ch7'], 'hunt-5-beaver': ['ch7'],
    'animal-alligator': ['ch6', 'thats-murfree-country'],
    'loot-gold-braithwaite': ['ch4'], 'loot-gold-shady-belle': ['ch3'],
    'loot-home-willard': ['ch6', 'start-charlotte'], 'loot-home-lonnie': ['ch3'],
  },
};
